name: Slack Notification Test

on:
  push:
    branches:
      - main

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack message on completion
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: python data/slack_test_result_script.py